### ISSUE TITLE
wrong language

### ISSUE THREAD

**Issue by ds2643** [AndreaOrru/X#1]
should be in D

**Comment by AndreaOrru** [comment]
inDeed

**Comment by andrewrk** [comment]
You misspelled zig (edit: oops I thought you were joking, never mind!)

**Comment by andrewrk** [comment]
Is this to have better API interop with LLVM C++ API?

**Comment by AndreaOrru** [comment]
Already answered in person but: no, I'm actually giving up on native code generation. It's going to target a VM. Also I want to get better at D and it's a good chance to do so. :)
